on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Print Working Directory
        run: |
          pwd
          ls
          ls -a
      
      - name: Read Environment Variables from JSON
        run: |
          VARIABLES=$(cat /home/runner/work/kubernetes/kubernetes/env.json | jq -r 'to_entries | map("\(.key)=\(.value | tostring)") | .[]')

          # Set the environment variables
          echo "$VARIABLES" >> $GITHUB_ENV

      - name: Use Environment Variables
        run: |
          for var in "${!IMAGE_@}"; do
            echo "Variable from JSON file: $var=${!var}"
          done


      # - name: Use Environment Variables
      #   run: |
      #     echo "Variable from JSON file: $IMAGE_1 $IMAGE_2"