name: Check variable file

on:
  push:
    branches:
      -main

jobs:
  Test:
    runs-on: ubuntu-latest

steps:
  - name: Clone Repo
    uses: actions/checkout@v4

  - name: present working directory
    run: |
      pwd
      ls
      ls -a