name: DRYing code

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read variables from JSON file
      id: read-env
      run: |
        # Read the JSON file into a variable
        ENVIRONMENT=$(cat /home/runner/work/kubernetes/kubernetes/env.json)
        
        # Set environment variables
        echo "IMAGES=$(echo "$ENVIRONMENT" | jq -r '.images | join(" ")')" >> $GITHUB_ENV
        echo "ACR_REGISTRY=$(echo "$ENVIRONMENT" | jq -r '.acr_registry')" >> $GITHUB_ENV
        echo "PLATFORM=$(echo "$ENVIRONMENT" | jq -r '.platform')" >> $GITHUB_ENV
        echo "AWS_REGISTRY=$(echo "$ENVIRONMENT" | jq -r '.acr_registry')" >> $GITHUB_ENV

    - name: Pull Docker images
      run: |
        for image in $IMAGES; do
          docker pull --platform $PLATFORM $image
        done

    - name: Change tags of images
      run: |
        for image in $IMAGES; do
          docker tag $ACR_REGISTRY/$image $AWS_REGISTRY/$image
        done


    # - name: Print environment variables
    #   run: |
    #     # Access the environment variables
    #     echo "Images:"
    #     for image in $IMAGES; do
    #       echo "  \$image: $image"
    #     done
        
    #     echo "ACR Registry: $ACR_REGISTRY"
    #     echo "Platform: $PLATFORM"

