name: DRYing code

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read variables from JSON file
      id: read-env
      run: |
        ENVIRONMENT=$(cat /home/runner/work/kubernetes/kubernetes/env.json)
        echo "::set-output name=environment::$ENVIRONMENT"

    - name: Echo variables
      run: |
        ENVIRONMENT=$(echo "${{ steps.read-env.outputs.environment }}")
        for key in $(echo "${!ENVIRONMENT[@]}"); do
          echo "$key=${ENVIRONMENT[$key]}"
        done