name: DRYing code

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Read variables from JSON file
      id: read-env
      run: |
        ENVIRONMENT=$(cat /home/runner/work/kubernetes/kubernetes/env.json)
        echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV

    - name: Parse environment variables
      run: |
        IMAGES=$(jq -r '.images[]' <<< "$ENVIRONMENT")
        ACR_REGISTRY=$(jq -r '.acr_registry' <<< "$ENVIRONMENT")
        PLATFORM=$(jq -r '.platform' <<< "$ENVIRONMENT")
        echo "Images:"
        for image in $IMAGES; do
          echo "  \$image: $image"
        done
        echo "ACR Registry: \$ACR_REGISTRY"
        echo "Platform: \$PLATFORM"

