on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Print Working Directory
        run: |
          pwd
          ls
          ls -a
      
      - name: Read Environment Variables from JSON
        run: |
          VARIABLES=$(cat path/to/your/env.json | jq -r 'to_entries | map("\(.key)=\(.value | tostring)") | .[]')

          # Set the environment variables
          echo "$VARIABLES" >> $GITHUB_ENV

      - name: Use Environment Variables
        run: |
          echo "Variable from JSON