name: DRYing code

on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read variables from JSON file
      id: read-env
      run: |
        ENVIRONMENT=$(cat /home/runner/work/kubernetes/kubernetes/env.json)
        echo "::set-output name=environment::$ENVIRONMENT"


    - name: Echo specific variables
      run: |
        ENVIRONMENT=$(echo "${{ steps.read-env.outputs.environment }}")
        IMAGES=$(echo "$ENVIRONMENT" | jq -r '.images[]')
        PLATFORM=$(echo "$ENVIRONMENT" | jq -r '.platform')
        ACR_REGISTRY=$(echo "$ENVIRONMENT" | jq -r '.acr_registry')
        
        echo "Platform: $PLATFORM"
        echo "ACR Registry: $ACR_REGISTRY"